# Generated by Django 4.2.2 on 2023-06-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
